export const IF_MATCH_HEADER = 'if-match';
export const IF_NONE_MATCH_HEADER = 'if-none-match';
export const ETAG_HEADER = 'etag';

export const OCC_ERROR_CODES = {
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',
  CONCURRENT_MODIFICATION_CONFLICT: 'CONCURRENT_MODIFICATION_CONFLICT',
  PRECONDITION_REQUIRED: 'PRECONDITION_REQUIRED',
} as const;
